### PR TITLE
Update badges and twitter link

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Update the twitter link to https
- Will update the badges throughout all projects without having to change the READMEs

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks so much - I really like the https change. Just changing the size of the buttons does not work for me I use these in several places and changing their size might look bad in some cases

**Comment by TacoTheDank** [comment]
I don't know how big they are compared to the old badges, but they should be equal to each other.

**Comment by ligi** [comment]
Selection_439

**Comment by TacoTheDank** [comment]
@ligi Ah yeah. I meant the new badges should be equal in size to the other new badges, not the old against the new.

I could change their heights to the 60px.

**Comment by TacoTheDank** [comment]
@ligi How about this?

EDIT: Actually hold on, I'll resize it again to match the previous badges.

**Comment by TacoTheDank** [comment]
Would you like me to get rid of the whitespace? Or is it fine now?

**Review by ligi — APPROVED** [review]
Nice! thanks!!

**Pull request merged**
